// Generated by LiveScript 1.6.0
(function(){
  var express, get, ref$, useProxy, proxyAddress, constantRateUsd, port, ip, tokenSymbol, proxy, constant, handler;
  express = require('express');
  get = require('superagent').get;
  ref$ = require('./config.json'), useProxy = ref$.useProxy, proxyAddress = ref$.proxyAddress, constantRateUsd = ref$.constantRateUsd, port = ref$.port, ip = ref$.ip, tokenSymbol = ref$.tokenSymbol;
  proxy = function(req, res){
    return get(proxyAddress).end(function(err, data){
      if (err != null) {
        return res.status(400).send(err + "");
      }
      return res.send(data.body);
    });
  };
  constant = function(req, res){
    var ref$;
    return res.send((ref$ = {}, ref$[tokenSymbol + ""] = {
      USD: constantRateUsd
    }, ref$));
  };
  handler = (function(){
    switch (false) {
    case !useProxy:
      return proxy;
    default:
      return constant;
    }
  }());
  express().get('/rate', handler).listen(port, ip);
}).call(this);
